### ISSUE TITLE
Trouble with connection to LibriVox 

### ISSUE THREAD

**Issue by axsesolga** [xenotropic/librivox-sqlite#1]
Hello!
First of all thank you for sharing that code!
I have an issue and pretty sure it is connected with ..connection by links in your code. But I am rookie so the trouble might be in other places.

So: no connection to `"https://librivox.org/api/feed/audiobooks?limit="$set_size` (I checked with
 [that](https://stackoverflow.com/questions/4860365/determine-in-php-script-if-connected-to-internet) code) but it works on any browser. 

Could you please check if it works for you

Thanks
![Безымянный](https://user-images.githubusercontent.com/33859194/66481621-f60e0f80-eaa9-11e9-82bd-59831c0cf2c3.png)

**Comment by xenotropic** [comment]
I don't see this issue on the instance that I have, and especially since it works from any browser it seems likely there is something wrong with the internet connectivity to your script. Sorry for the delay, and that I couldn't be of more help.
